import {
  Wifi,
  Waves,
  Dumbbell,
  Car,
  Utensils,
  Snowflake,
  Sparkles,
  Wine,
  Coffee,
  Tv,
  Shield,
  Bath,
  Refrigerator,
  WashingMachine,
  Users,
  Baby,
  PawPrint,
  Briefcase,
  HeartPulse,
  ConciergeBell,
  ParkingCircle,
  CigaretteOff,
  Accessibility,
  Bike,
  Bus,
  TreePalm,
  Gamepad2,
  Music,
  Camera,
  ShieldCheck,
  CircleHelp,
} from "lucide-react";

export const amenityIcons = {
  WiFi: Wifi,
  Pool: Waves,
  Gym: Dumbbell,
  Parking: Car,
  Restaurant: Utensils,
  AC: Snowflake,
  Spa: Sparkles,
  Bar: Wine,
  "Coffee Shop": Coffee,
  TV: Tv,
  Security: Shield,
  Bathtub: Bath,
  Refrigerator: Refrigerator,
  Laundry: WashingMachine,
  "Family Rooms": Users,
  "Kids Play Area": Baby,
  "Pet Friendly": PawPrint,
  "Business Center": Briefcase,
  "Medical Assistance": HeartPulse,
  RoomService: ConciergeBell,
  "Free Parking": ParkingCircle,
  "Non Smoking": CigaretteOff,
  Accessible: Accessibility,
  Bicycle: Bike,
  Shuttle: Bus,
  Garden: TreePalm,
  Gaming: Gamepad2,
  Entertainment: Music,
  CCTV: Camera,
  "24x7 Security": ShieldCheck,
};

export const DefaultAmenityIcon = CircleHelp;
